apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: sanket-cloud-run-pipeline
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: [dev]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Cloud Run development svc
run:
 location: projects/$PROJECT_ID/locations/us-central1







